### PR TITLE
Fix build errors when using UIKit for Mac (Project Catalyst)

### PR DESCRIPTION
**Pull request by revolter**
Thanks for proposing a pull request.

To help us review the request, please complete the following:

- [x] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [x] describe the change (for example, what happens before the change, and after the change)

I replaced the deprecated UIWebView that isn't available on macOS with WKWebView.

### CODE REVIEW

**Comment by EmperiorEric** [comment]
Any chance these will get merged soon? Or is there a separate branch to be looking at with this fixed?

**Comment by ArtFeel** [comment]
Merge please 🙏

**Comment by joesus** [comment]
Carthage build failed which is sort of a problem. Haven't had a chance to dig into this yet. @revolter, if you have time to look into the Carthage failure, I'll be looking at the other two open PRs and seeing about getting those merged. Thanks for the contribution!

**Comment by Brian-Co** [comment]
Thanks for this PR 🙏 FBSDK is now the last dependency preventing me from building on Catalyst right now. Hope to be able to try this asap! 👍

**Comment by dreamolight** [comment]
We've made a few changes to make FB SDK catalyst compatible which has conflicts with this PR, so closing this one.

**Comment by revolter** [comment]
It's weird that it took Facebook 1 month for this. And, what does "x imported this PR" mean then? I thought it means that it gets merged.

**Comment by dreamolight** [comment]
First of all, thanks for bring this up, we wouldn't notice the catalyst compatibility issue without your PR! Imported means this PR gets into our internal code review system, however, this PR didn't pass our internal build system, hence the PR was on hold, and in the meantime we were distracted by other internal projects. We re-opened the `issues` tab recently, and are still getting used to it, sorry for the inconvenience during the period, we'll keep improving the response time on issues.

**Comment by revolter** [comment]
> We've made a few changes to make FB SDK catalyst compatible which has conflicts with this PR, so closing this one.

From what I noticed, you didn't actually "closed this one" in favour of your own changes, you actually did took my changes, apparently without crediting me.

**Pull request closed without merging**
