### PR TITLE
Adds nullability annotation to solve static analyser issue

### PR DESCRIPTION
**Pull request by valeriyvan**
Thanks for proposing a pull request.

To help us review the request, please complete the following:

- [ x] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [x ] describe the change (for example, what happens before the change, and after the change)

### CODE REVIEW

**Comment by valeriyvan** [comment]
In FBSDKWebViewAppLinkResolver.m on line 277 this method might be called with appLinkTargetWithURL parameter nil. Parameter is created on line 274 and it might be nil.
Run static analyzer.
It really helps to see things you think are impossible.

**Comment by valeriyvan** [comment]
File `FBSDKWebViewAppLinkResolver.m`.
Local variable `destination` is declared on line 289, not initialized (in modern Objective-C it is guaranteed to be nil) and passed on line 299 in call of [FBSDKAppLink appLinkWithSourceURL:targets:webURL:] in first parameter.

Or nullable declaration is needed. 
Or caller code is wrong.

**Comment by valeriyvan** [comment]
You are right.
It seems static analyzer was false positive here.
I have added `nonnul`l annotation to internal method to help static analyzer and this solved issue.

**Comment by robtimp** [comment]
@valeriyvan Thank you. We’ll be adding nullability and type annotations with an upcoming version. We’re holding off until then since it will cause breaking changes for users of the SDK from Swift.

**Pull request closed without merging**
